# Generated by Django 5.2.4 on 2025-09-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comentario_autor'),
        ('heroes', '0002_hero_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heroes.hero'),
            preserve_default=False,
        ),
    ]
