# Generated by Django 5.2.4 on 2025-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='herois/'),
        ),
    ]
