# Generated by Django 5.2.4 on 2025-10-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_villain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Villain',
        ),
    ]
